from __future__ import annotations

import json
from typing import Protocol

from src.config import AppConfig
from src.models import AnalysisResult
from src.prompts import SYSTEM_PROMPT, build_user_prompt


class AnalysisError(RuntimeError):
    """Raised when a document analysis provider fails."""


class AnalysisProvider(Protocol):
    name: str

    def analyze(
        self,
        *,
        text: str,
        document_type: str,
        detected_language: str,
        response_language: str,
    ) -> AnalysisResult:
        """Analyze the extracted document text."""


class MockAnalysisProvider:
    name = "mock"

    def analyze(
        self,
        *,
        text: str,
        document_type: str,
        detected_language: str,
        response_language: str,
    ) -> AnalysisResult:
        excerpt = " ".join(text.split())[:500]
        return {
            "executive_summary": {
                "customer_overview": "Mock analysis mode. Customer details were not inferred with an AI model.",
                "opportunity_overview": (
                    f"Detected a {document_type} document in {detected_language}. "
                    "This mock output validates the Milestone 1 pipeline without OpenAI credentials."
                ),
                "key_objectives": [
                    "Extract text from the PDF.",
                    "Detect document language.",
                    "Classify the procurement document type.",
                    "Generate the required output files.",
                ],
                "major_requirements": [
                    "Review the source document manually or run the OpenAI provider in a future milestone for deeper extraction."
                ],
                "risks": [
                    "Mock mode does not perform semantic requirement extraction.",
                    "Fit assessments are placeholders until a real analysis provider is selected.",
                ],
                "recommendations": [
                    "Use this mode for local smoke tests, CI checks, and architecture validation."
                ],
            },
            "document_type": document_type,
            "detected_language": detected_language,
            "response_language": response_language,
            "customer_context": {
                "organization": "Unknown",
                "industry": "Unknown",
                "business_problem": "Unknown",
                "procurement_goal": "Unknown",
            },
            "key_dates": [],
            "requirements": [
                {
                    "requirement_id": "REQ-MOCK-001",
                    "category": "Technical",
                    "requirement_description": "PDF text extraction completed successfully.",
                    "mandatory_or_optional": "Unknown",
                    "fit_assessment": "Needs review",
                    "notes": f"Text excerpt: {excerpt}",
                },
                {
                    "requirement_id": "REQ-MOCK-002",
                    "category": "Compliance",
                    "requirement_description": "Document language and response language were detected locally.",
                    "mandatory_or_optional": "Unknown",
                    "fit_assessment": "Needs review",
                    "notes": f"Detected response language: {response_language}",
                },
            ],
            "risks": [
                {
                    "risk_id": "RISK-MOCK-001",
                    "description": "Output is generated by mock rules, not by full AI analysis.",
                    "impact": "The generated business insights are not suitable for final proposal decisions.",
                    "probability": "High",
                    "mitigation": "Select the OpenAI provider once API credentials are configured.",
                    "owner": "SE",
                }
            ],
            "clarification_questions": [
                {
                    "question": "Which provider should be used for the final analysis once Milestone 1 validation is complete?",
                    "reason": "Mock mode is intended for local execution without external credentials.",
                    "owner": "SE",
                }
            ],
            "go_no_go": {
                "recommendation": "CONDITIONAL GO",
                "executive_recommendation": "Proceed with local validation; use a real analysis provider before customer-facing decisions.",
                "key_strengths": [
                    "The command-line workflow runs without OpenAI credentials.",
                    "The required output artifacts are generated.",
                ],
                "key_concerns": [
                    "Mock mode does not extract detailed commercial, legal, or security requirements."
                ],
                "recommended_next_actions": [
                    "Validate output file generation.",
                    "Add automated tests around provider selection.",
                ],
            },
            "solution_outline": {
                "overview": "Generic architecture for a local command-line procurement document analyzer.",
                "approach": [
                    "Read a PDF from disk.",
                    "Extract text locally.",
                    "Run local detection rules.",
                    "Inject an analysis provider.",
                    "Write Markdown, Excel, and JSON outputs.",
                ],
                "architecture_components": [
                    "PDF extractor",
                    "Language detector",
                    "Document classifier",
                    "Analysis provider interface",
                    "Output writer",
                ],
                "delivery_considerations": [
                    "Keep OpenAI integration optional until future milestones.",
                    "Avoid requiring secrets for local smoke tests.",
                ],
                "assumptions": [
                    "The input PDF contains extractable text.",
                    "Mock outputs are acceptable for Milestone 1 validation.",
                ],
            },
            "recommended_next_steps": [
                "Run the app against a sample PDF.",
                "Inspect all seven generated output files.",
                "Select the OpenAI provider only when credentials are available.",
            ],
        }


class OpenAIAnalysisProvider:
    name = "openai"

    _MAX_RETRIES = 3
    _RETRY_BASE_DELAY = 2.0

    def __init__(self, *, api_key: str, model: str, reasoning_effort: str | None = None) -> None:
        self.api_key = api_key
        self.model = model
        self.reasoning_effort = reasoning_effort

    def analyze(
        self,
        *,
        text: str,
        document_type: str,
        detected_language: str,
        response_language: str,
    ) -> AnalysisResult:
        import time

        try:
            from openai import APIConnectionError, APIStatusError, OpenAI, RateLimitError
        except ImportError as exc:
            raise AnalysisError(
                "The openai package is not installed. Run: pip install -r requirements.txt"
            ) from exc

        client = OpenAI(api_key=self.api_key, timeout=60.0)
        prompt = build_user_prompt(
            text=text,
            document_type=document_type,
            detected_language=detected_language,
            response_language=response_language,
        )

        extra_kwargs: dict[str, object] = {}
        if self.reasoning_effort is not None:
            extra_kwargs["reasoning"] = {"effort": self.reasoning_effort}
        else:
            extra_kwargs["temperature"] = 0.2

        last_exc: Exception | None = None
        for attempt in range(self._MAX_RETRIES):
            try:
                response = client.responses.create(
                    model=self.model,
                    input=[
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": prompt},
                    ],
                    **extra_kwargs,
                )
                content = response.output_text.strip()
                if not content:
                    raise AnalysisError("OpenAI returned an empty response.")

                try:
                    return json.loads(content)
                except json.JSONDecodeError as exc:
                    raise AnalysisError("OpenAI returned invalid JSON.") from exc

            except RateLimitError as exc:
                last_exc = exc
                if attempt < self._MAX_RETRIES - 1:
                    delay = self._RETRY_BASE_DELAY * (2 ** attempt)
                    time.sleep(delay)

            except APIConnectionError as exc:
                raise AnalysisError(
                    "Could not connect to the OpenAI API. Check your network connection."
                ) from exc

            except APIStatusError as exc:
                raise AnalysisError(
                    f"OpenAI API returned an error: HTTP {exc.status_code}."
                ) from exc

            except AnalysisError:
                raise

            except Exception as exc:
                raise AnalysisError(f"Unexpected API failure: {exc}") from exc

        raise AnalysisError(
            f"OpenAI rate limit reached after {self._MAX_RETRIES} attempts. Wait a moment and try again."
        ) from last_exc


def build_analysis_provider(config: AppConfig) -> AnalysisProvider:
    if config.provider == "mock":
        return MockAnalysisProvider()
    if config.provider == "openai":
        if not config.api_key:
            raise AnalysisError(
                "OPENAI_API_KEY is required when the openai provider is selected."
            )
        return OpenAIAnalysisProvider(
            api_key=config.api_key,
            model=config.model,
            reasoning_effort=config.reasoning_effort,
        )
    raise AnalysisError(f"Unsupported analysis provider: {config.provider}")
