from __future__ import annotations

import json
from typing import Protocol

from src.config import AppConfig
from src.models import AnalysisResult
from src.prompts import SYSTEM_PROMPT, build_user_prompt


class AnalysisError(RuntimeError):
    """Raised when a document analysis provider fails."""


class AnalysisProvider(Protocol):
    name: str

    def analyze(
        self,
        *,
        text: str,
        document_type: str,
        detected_language: str,
        response_language: str,
    ) -> AnalysisResult:
        """Analyze the extracted document text."""


class MockAnalysisProvider:
    name = "mock"

    def analyze(
        self,
        *,
        text: str,
        document_type: str,
        detected_language: str,
        response_language: str,
    ) -> AnalysisResult:
        excerpt = " ".join(text.split())[:500]
        return {
            "executive_summary": {
                "customer_overview": "Mock analysis mode. Customer details were not inferred with an AI model.",
                "opportunity_overview": (
                    f"Detected a {document_type} document in {detected_language}. "
                    "This mock output validates the Milestone 1 pipeline without OpenAI credentials."
                ),
                "key_objectives": [
                    "Extract text from the PDF.",
                    "Detect document language.",
                    "Classify the procurement document type.",
                    "Generate the required output files.",
                ],
                "major_requirements": [
                    "Review the source document manually or run the OpenAI provider in a future milestone for deeper extraction."
                ],
                "risks": [
                    "Mock mode does not perform semantic requirement extraction.",
                    "Fit assessments are placeholders until a real analysis provider is selected.",
                ],
                "recommendations": [
                    "Use this mode for local smoke tests, CI checks, and architecture validation."
                ],
            },
            "document_type": document_type,
            "detected_language": detected_language,
            "response_language": response_language,
            "customer_context": {
                "organization": "Unknown",
                "industry": "Unknown",
                "business_problem": "Unknown",
                "procurement_goal": "Unknown",
            },
            "key_dates": [],
            "requirements": [
                {
                    "requirement_id": "REQ-MOCK-001",
                    "category": "Technical",
                    "requirement_description": "PDF text extraction completed successfully.",
                    "mandatory_or_optional": "Unknown",
                    "fit_assessment": "Needs review",
                    "notes": f"Text excerpt: {excerpt}",
                },
                {
                    "requirement_id": "REQ-MOCK-002",
                    "category": "Compliance",
                    "requirement_description": "Document language and response language were detected locally.",
                    "mandatory_or_optional": "Unknown",
                    "fit_assessment": "Needs review",
                    "notes": f"Detected response language: {response_language}",
                },
            ],
            "risks": [
                {
                    "risk_id": "RISK-MOCK-001",
                    "description": "Output is generated by mock rules, not by full AI analysis.",
                    "impact": "The generated business insights are not suitable for final proposal decisions.",
                    "probability": "High",
                    "mitigation": "Select the OpenAI provider once API credentials are configured.",
                    "owner": "SE",
                }
            ],
            "clarification_questions": [
                {
                    "question": "Which provider should be used for the final analysis once Milestone 1 validation is complete?",
                    "reason": "Mock mode is intended for local execution without external credentials.",
                    "owner": "SE",
                }
            ],
            "go_no_go": {
                "recommendation": "CONDITIONAL GO",
                "executive_recommendation": "Proceed with local validation; use a real analysis provider before customer-facing decisions.",
                "key_strengths": [
                    "The command-line workflow runs without OpenAI credentials.",
                    "The required output artifacts are generated.",
                ],
                "key_concerns": [
                    "Mock mode does not extract detailed commercial, legal, or security requirements."
                ],
                "recommended_next_actions": [
                    "Validate output file generation.",
                    "Add automated tests around provider selection.",
                ],
            },
            "solution_outline": {
                "overview": "Generic architecture for a local command-line procurement document analyzer.",
                "approach": [
                    "Read a PDF from disk.",
                    "Extract text locally.",
                    "Run local detection rules.",
                    "Inject an analysis provider.",
                    "Write Markdown, Excel, and JSON outputs.",
                ],
                "architecture_components": [
                    "PDF extractor",
                    "Language detector",
                    "Document classifier",
                    "Analysis provider interface",
                    "Output writer",
                ],
                "delivery_considerations": [
                    "Keep OpenAI integration optional until future milestones.",
                    "Avoid requiring secrets for local smoke tests.",
                ],
                "assumptions": [
                    "The input PDF contains extractable text.",
                    "Mock outputs are acceptable for Milestone 1 validation.",
                ],
            },
            "recommended_next_steps": [
                "Run the app against a sample PDF.",
                "Inspect all seven generated output files.",
                "Select the OpenAI provider only when credentials are available.",
            ],
        }


class OpenAIAnalysisProvider:
    name = "openai"

    def __init__(self, *, api_key: str, model: str) -> None:
        self.api_key = api_key
        self.model = model

    def analyze(
        self,
        *,
        text: str,
        document_type: str,
        detected_language: str,
        response_language: str,
    ) -> AnalysisResult:
        try:
            from openai import OpenAI
        except ImportError as exc:
            raise AnalysisError(
                "The openai package is not installed. Run: pip install -r requirements.txt"
            ) from exc

        client = OpenAI(api_key=self.api_key)
        prompt = build_user_prompt(
            text=text,
            document_type=document_type,
            detected_language=detected_language,
            response_language=response_language,
        )

        try:
            response = client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": prompt},
                ],
                response_format={"type": "json_object"},
                temperature=0.2,
            )
        except Exception as exc:
            raise AnalysisError(f"OpenAI API request failed: {exc}") from exc

        content = response.choices[0].message.content
        if not content:
            raise AnalysisError("OpenAI API returned an empty response.")

        try:
            parsed = json.loads(content)
        except json.JSONDecodeError as exc:
            raise AnalysisError("OpenAI API returned invalid JSON.") from exc

        return parsed


def build_analysis_provider(config: AppConfig) -> AnalysisProvider:
    if config.provider == "mock":
        return MockAnalysisProvider()
    if config.provider == "openai":
        if not config.api_key:
            raise AnalysisError(
                "OPENAI_API_KEY is required when the openai provider is selected."
            )
        return OpenAIAnalysisProvider(api_key=config.api_key, model=config.model)
    raise AnalysisError(f"Unsupported analysis provider: {config.provider}")
